version: '3'

services:
  lbdb:
    container_name: lbdb
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - '5432:5432'

  lbapi: &lbapi
    container_name: lbapi
    build:
      context: ./lanebreach-api
      dockerfile: Dockerfile
    image: lanebreach_api
    environment:
      RAILS_DATABASE_HOST: lbdb
      REDIS_URL: redis://redis:6379
    volumes:
      - ./lanebreach-api:/lanebreach-api
    ports:
      - '3000:3000'
    depends_on:
      - lbdb
    command: bundle exec puma

  worker:
    <<: *lbapi
    container_name: worker
    image: lanebreach_worker
    ports: []
    depends_on:
      - redis
    command: bundle exec sidekiq

  redis:
    image: redis:5.0-alpine
    container_name: redis
